//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lr6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public int Load_capacity { get; set; }
        public string Condition { get; set; }
        public string Location { get; set; }
        public string Number { get; set; }
        public float Fuel_consuption { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
